# Generated by Django 5.2.15 on 2026-06-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='이벤트 ID')),
                ('title', models.CharField(db_column='title', max_length=150, verbose_name='일정 제목')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='상세 내용')),
                ('start_time', models.DateTimeField(db_column='starttime', verbose_name='시작 일시')),
                ('end_time', models.DateTimeField(db_column='endtime', verbose_name='종료 일시')),
                ('color', models.CharField(db_column='color', default='#3788D8', max_length=7, verbose_name='색상 코드')),
                ('event_type', models.CharField(db_column='eventtype', default='MANUAL', max_length=30, verbose_name='이벤트 유형')),
                ('is_all_day', models.BooleanField(db_column='isallday', default=False, verbose_name='종일 일정 여부')),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='employees.employee', verbose_name='담당 직원')),
            ],
            options={
                'verbose_name': '캘린더 일정',
                'verbose_name_plural': '캘린더 일정 목록',
                'db_table': 'calendarevent',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='고정 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='employees.employee', verbose_name='작성자')),
            ],
            options={
                'db_table': 'memo',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='업무 ID')),
                ('title', models.CharField(db_column='title', max_length=150, verbose_name='업무명')),
                ('content', models.TextField(db_column='content', verbose_name='업무 내용')),
                ('status', models.CharField(db_column='status', default='TODO', max_length=20, verbose_name='진행 상태')),
                ('priority', models.CharField(db_column='priority', default='MEDIUM', max_length=10, verbose_name='우선순위')),
                ('due_date', models.DateField(blank=True, db_column='duedate', null=True, verbose_name='마감 기한')),
                ('is_ai_recommended', models.BooleanField(db_column='is_ai_recommended', default=False, verbose_name='AI 추천 여부')),
                ('reference_target', models.CharField(blank=True, db_column='reference_target', max_length=50, null=True, verbose_name='참조 데이터 소스')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat', verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat', verbose_name='수정 일시')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completedat', null=True, verbose_name='완료 일시')),
                ('assignee', models.ForeignKey(db_column='assignee_id', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='employees.employee', verbose_name='담당자')),
                ('creator', models.ForeignKey(blank=True, db_column='creator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='employees.employee', verbose_name='지시자/생성자')),
            ],
            options={
                'verbose_name': '할 일(Task)',
                'verbose_name_plural': '할 일(Task) 목록',
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='댓글 ID')),
                ('comment', models.TextField(db_column='comment', verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat', verbose_name='작성 일시')),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='작성자')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='works.task', verbose_name='소속 업무')),
            ],
            options={
                'verbose_name': '업무 댓글',
                'verbose_name_plural': '업무 댓글 목록',
                'db_table': 'taskcomment',
            },
        ),
        migrations.CreateModel(
            name='WorkNotification',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='알림 ID')),
                ('message', models.CharField(db_column='message', max_length=255, verbose_name='알림 내용')),
                ('is_read', models.BooleanField(db_column='is_read', default=False, verbose_name='읽음 여부')),
                ('redirect_url', models.CharField(blank=True, db_column='redirect_url', max_length=200, null=True, verbose_name='이동 URL 경로')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat', verbose_name='알림 발생 일시')),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee', verbose_name='수신 직원')),
            ],
            options={
                'verbose_name': '업무 알림',
                'verbose_name_plural': '업무 알림 목록',
                'db_table': 'worknotification',
                'ordering': ['-created_at'],
            },
        ),
    ]
