# Generated by Django 5.2.15 on 2026-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_add_memo_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-is_pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='memo',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='고정 여부'),
        ),
    ]
