# Generated by Django 5.2.15 on 2026-06-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('ssafy_international', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7)),
                ('costcenter', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KRW', max_length=8)),
            ],
            options={
                'verbose_name': '예산',
                'verbose_name_plural': '예산 목록',
                'db_table': 'budget',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7)),
                ('category', models.CharField(max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KRW', max_length=8)),
                ('costcenter', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': '일반 경비',
                'verbose_name_plural': '일반 경비 목록',
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoicedate', models.DateField()),
                ('duedate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KRW', max_length=8)),
                ('paymentterms', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('purchaseorderid', models.ForeignKey(db_column='purchaseorderid', on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='procurement.purchaseorder')),
                ('supplierid', models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='ssafy_international.supplier')),
            ],
            options={
                'verbose_name': '매입채무',
                'verbose_name_plural': '매입채무 목록',
                'db_table': 'accountspayable',
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoicedate', models.DateField()),
                ('duedate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KRW', max_length=8)),
                ('paymentterms', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('customerid', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='ssafy_international.customer')),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='ssafy_international.order')),
            ],
            options={
                'verbose_name': '매출채권',
                'verbose_name_plural': '매출채권 목록',
                'db_table': 'accountsreceivable',
            },
        ),
    ]
