# Generated by Django 5.2.15 on 2026-06-23 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, choices=[('대표이사', '대표이사'), ('Vice President, Sales', 'Vice President, Sales'), ('Sales Manager', 'Sales Manager'), ('Inside Sales Coordinator', 'Inside Sales Coordinator'), ('Sales Representative', 'Sales Representative')], max_length=60, null=True)),
                ('titleofcourtesy', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('homephone', models.CharField(blank=True, max_length=40, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photopath', models.CharField(blank=True, max_length=200, null=True)),
                ('reportsto', models.ForeignKey(blank=True, db_column='reportsto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='employees.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='employees.employee')),
            ],
            options={
                'db_table': 'employeeterritory',
            },
        ),
    ]
