# Generated by Django 5.2.15 on 2026-06-24 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('연차', '연차'), ('병가', '병가'), ('경조사', '경조사'), ('기타', '기타')], db_column='leave_type', default='연차', max_length=10, verbose_name='휴가종류')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='시작일')),
                ('end_date', models.DateField(db_column='end_date', verbose_name='종료일')),
                ('days', models.DecimalField(db_column='days', decimal_places=1, default=1, max_digits=4, verbose_name='일수')),
                ('reason', models.CharField(blank=True, db_column='reason', max_length=200, null=True, verbose_name='신청 사유')),
                ('status', models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('반려', '반려')], db_column='status', default='대기', max_length=10, verbose_name='상태')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_column='applied_at', verbose_name='신청일시')),
                ('processed_at', models.DateTimeField(blank=True, db_column='processed_at', null=True, verbose_name='처리일시')),
            ],
            options={
                'verbose_name': '휴가 신청',
                'verbose_name_plural': '휴가 신청 목록',
                'db_table': 'leaverequest',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('title', models.CharField(blank=True, choices=[('대표이사', '대표이사'), ('Vice President, Sales', 'Vice President, Sales'), ('Sales Manager', 'Sales Manager'), ('Inside Sales Coordinator', 'Inside Sales Coordinator'), ('Sales Representative', 'Sales Representative')], max_length=60, null=True)),
                ('titleofcourtesy', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('region', models.CharField(blank=True, max_length=60, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('homephone', models.CharField(blank=True, max_length=40, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photopath', models.CharField(blank=True, max_length=200, null=True)),
                ('reportsto', models.ForeignKey(blank=True, db_column='reportsto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='employees.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', verbose_name='날짜')),
                ('checkin_time', models.TimeField(blank=True, db_column='checkin_time', null=True, verbose_name='출근 시간')),
                ('checkout_time', models.TimeField(blank=True, db_column='checkout_time', null=True, verbose_name='퇴근 시간')),
                ('status', models.CharField(choices=[('정상', '정상'), ('지각', '지각'), ('조퇴', '조퇴'), ('결근', '결근'), ('휴가', '휴가')], db_column='status', default='정상', max_length=10, verbose_name='상태')),
                ('note', models.CharField(blank=True, db_column='note', max_length=200, null=True, verbose_name='비고')),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '근태',
                'verbose_name_plural': '근태 목록',
                'db_table': 'attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='employees.employee')),
            ],
            options={
                'db_table': 'employeeterritory',
            },
        ),
    ]
