# Generated by Django 5.2.15 on 2026-06-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('ssafy_international', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeterritory',
            name='territoryid',
            field=models.ForeignKey(db_column='territoryid', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='ssafy_international.territory'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeterritory',
            unique_together={('employeeid', 'territoryid')},
        ),
    ]
