# Generated by Django 5.2.15 on 2026-06-24 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('ssafy_international', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeterritory',
            name='territoryid',
            field=models.ForeignKey(db_column='territoryid', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='ssafy_international.territory'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approver',
            field=models.ForeignKey(blank=True, db_column='approver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leave_requests', to='employees.employee', verbose_name='처리자'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='신청자'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeterritory',
            unique_together={('employeeid', 'territoryid')},
        ),
    ]
