# Generated by Django 5.2.15 on 2026-06-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', verbose_name='날짜')),
                ('checkin_time', models.TimeField(blank=True, db_column='checkin_time', null=True, verbose_name='출근 시간')),
                ('checkout_time', models.TimeField(blank=True, db_column='checkout_time', null=True, verbose_name='퇴근 시간')),
                ('status', models.CharField(choices=[('정상', '정상'), ('지각', '지각'), ('조퇴', '조퇴'), ('결근', '결근'), ('휴가', '휴가')], db_column='status', default='정상', max_length=10, verbose_name='상태')),
                ('note', models.CharField(blank=True, db_column='note', max_length=200, null=True, verbose_name='비고')),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='직원')),
            ],
            options={
                'verbose_name': '근태',
                'verbose_name_plural': '근태 목록',
                'db_table': 'attendance',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
