# Generated by Django 5.2.15 on 2026-06-24 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('연차', '연차'), ('병가', '병가'), ('경조사', '경조사'), ('기타', '기타')], db_column='leave_type', default='연차', max_length=10, verbose_name='휴가종류')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='시작일')),
                ('end_date', models.DateField(db_column='end_date', verbose_name='종료일')),
                ('days', models.DecimalField(db_column='days', decimal_places=1, default=1, max_digits=4, verbose_name='일수')),
                ('reason', models.CharField(blank=True, db_column='reason', max_length=200, null=True, verbose_name='신청 사유')),
                ('status', models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('반려', '반려')], db_column='status', default='대기', max_length=10, verbose_name='상태')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_column='applied_at', verbose_name='신청일시')),
                ('processed_at', models.DateTimeField(blank=True, db_column='processed_at', null=True, verbose_name='처리일시')),
                ('approver', models.ForeignKey(blank=True, db_column='approver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leave_requests', to='employees.employee', verbose_name='처리자')),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='신청자')),
            ],
            options={
                'verbose_name': '휴가 신청',
                'verbose_name_plural': '휴가 신청 목록',
                'db_table': 'leaverequest',
                'ordering': ['-applied_at'],
            },
        ),
    ]
