# Generated by Django 5.2.15 on 2026-06-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('ssafy_international', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('count_type', models.CharField(choices=[('정기', '정기'), ('특별', '특별'), ('수시', '수시')], db_column='count_type', default='정기', max_length=10)),
                ('scope', models.CharField(blank=True, max_length=100, null=True)),
                ('warehouse', models.CharField(max_length=40)),
                ('scheduled_date', models.DateField(db_column='scheduled_date')),
                ('status', models.CharField(choices=[('대기', '대기'), ('진행중', '진행중'), ('완료', '완료')], default='대기', max_length=10)),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_count_plans', to='employees.employee')),
            ],
            options={
                'db_table': 'inventorycountplan',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system_qty', models.IntegerField(default=0)),
                ('counted_qty', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.PROTECT, related_name='count_items', to='ssafy_international.product')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycountplan')),
            ],
            options={
                'db_table': 'inventorycountitem',
            },
        ),
    ]
