# Generated by Django 5.2.15 on 2026-06-24 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_seed_department_and_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(choices=[('설날', '설날'), ('추석', '추석'), ('성과', '성과'), ('특별', '특별')], default='성과', max_length=10)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('지급대기', '지급대기'), ('지급완료', '지급완료')], default='지급완료', max_length=10)),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='employees.employee')),
            ],
            options={
                'db_table': 'payroll_bonus',
                'ordering': ['-pay_date'],
            },
        ),
        migrations.CreateModel(
            name='Severance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_service', models.DecimalField(decimal_places=1, max_digits=5)),
                ('avg_monthly_wage', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('계산됨', '계산됨'), ('지급대기', '지급대기'), ('지급완료', '지급완료')], default='계산됨', max_length=10)),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='severances', to='employees.employee')),
            ],
            options={
                'db_table': 'payroll_severance',
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=14)),
                ('position_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_deduction', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('계산중', '계산중'), ('확정', '확정')], default='확정', max_length=10)),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employee')),
            ],
            options={
                'db_table': 'payroll_salaryrecord',
                'ordering': ['-period'],
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='YearEndSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_income', models.DecimalField(decimal_places=0, max_digits=14)),
                ('tax_withheld', models.DecimalField(decimal_places=0, max_digits=12)),
                ('determined_tax', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('정산중', '정산중'), ('정산완료', '정산완료')], default='정산완료', max_length=10)),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, related_name='year_end_settlements', to='employees.employee')),
            ],
            options={
                'db_table': 'payroll_yearendsettlement',
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
