# Generated by Django 5.2.15 on 2026-06-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platenumber', models.CharField(max_length=20)),
                ('capacitylabel', models.CharField(max_length=20)),
                ('capacitykg', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('dispatchdate', models.DateField()),
                ('drivername', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=100)),
                ('shipmentcount', models.IntegerField(default=0)),
                ('totalweightkg', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('departuretime', models.DateTimeField()),
                ('status', models.CharField(choices=[('waiting', '대기'), ('in_transit', '배송중'), ('completed', '완료')], default='waiting', max_length=20)),
                ('vehicleid', models.ForeignKey(db_column='vehicleid', on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='logistics.vehicle')),
            ],
            options={
                'db_table': 'dispatch',
                'ordering': ['departuretime'],
            },
        ),
    ]
