# Generated by Django 5.2.15 on 2026-06-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=100)),
                ('contactname', models.CharField(blank=True, max_length=100, null=True)),
                ('contacttitle', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(max_length=40)),
                ('fax', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.AutoField(primary_key=True, serialize=False)),
                ('regiondescription', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('shipperid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'shipper',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=100)),
                ('contactname', models.CharField(blank=True, max_length=100, null=True)),
                ('contacttitle', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(max_length=40)),
                ('fax', models.CharField(blank=True, max_length=60, null=True)),
                ('homepage', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateTimeField(null=True)),
                ('requireddate', models.DateTimeField(null=True)),
                ('shippeddate', models.DateTimeField(blank=True, null=True)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipname', models.CharField(blank=True, max_length=120, null=True)),
                ('shipaddress', models.CharField(blank=True, max_length=200, null=True)),
                ('shipcity', models.CharField(blank=True, max_length=60, null=True)),
                ('shipregion', models.CharField(blank=True, max_length=60, null=True)),
                ('shippostalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('shipcountry', models.CharField(blank=True, max_length=60, null=True)),
                ('customerid', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ssafy_international.customer')),
                ('employeeid', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='employees.employee')),
                ('shipvia', models.ForeignKey(db_column='shipvia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ssafy_international.shipper')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=100)),
                ('quantityperunit', models.CharField(blank=True, max_length=100, null=True)),
                ('unitprice', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unitsinstock', models.IntegerField(default=0)),
                ('unitsonorder', models.IntegerField(default=0)),
                ('reorderlevel', models.IntegerField(default=0)),
                ('discontinued', models.CharField(default='0', max_length=1)),
                ('categoryid', models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ssafy_international.category')),
                ('supplierid', models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ssafy_international.supplier')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField(default=0)),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='ssafy_international.order')),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.PROTECT, related_name='orderdetails', to='ssafy_international.product')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('territoryid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('territorydescription', models.CharField(max_length=200)),
                ('regionid', models.ForeignKey(db_column='regionid', on_delete=django.db.models.deletion.PROTECT, related_name='territories', to='ssafy_international.region')),
            ],
            options={
                'db_table': 'territory',
            },
        ),
    ]
