# Generated by Django 5.2.15 on 2026-06-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('ssafy_international', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('bomid', models.AutoField(primary_key=True, serialize=False)),
                ('bomcode', models.CharField(max_length=30)),
                ('productname', models.CharField(max_length=120)),
                ('bomtype', models.CharField(max_length=20)),
                ('basisquantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basisunit', models.CharField(max_length=10)),
                ('revision', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('allergen', models.CharField(blank=True, max_length=120, null=True)),
                ('batchcost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='KRW', max_length=8)),
            ],
            options={
                'db_table': 'bom',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('materialname', models.CharField(max_length=120)),
                ('materialtype', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
                ('unitcost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KRW', max_length=8)),
                ('allergen', models.CharField(blank=True, max_length=60, null=True)),
                ('supplierid', models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='ssafy_international.supplier')),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='BomComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('linecost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bomid', models.ForeignKey(db_column='bomid', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='procurement.bom')),
                ('materialid', models.ForeignKey(db_column='materialid', on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='procurement.material')),
            ],
            options={
                'db_table': 'bomcomponent',
            },
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('productid', models.OneToOneField(db_column='productid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cost', serialize=False, to='ssafy_international.product')),
                ('unitcost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='KRW', max_length=8)),
                ('leadtimedays', models.IntegerField(default=0)),
                ('moq', models.IntegerField(default=0)),
                ('safetystock', models.IntegerField(default=0)),
                ('preferredsupplierid', models.ForeignKey(db_column='preferredsupplierid', on_delete=django.db.models.deletion.PROTECT, related_name='preferred_products', to='ssafy_international.supplier')),
            ],
            options={
                'db_table': 'productcost',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('expecteddate', models.DateField(blank=True, null=True)),
                ('receiveddate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('currency', models.CharField(default='KRW', max_length=10)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalamount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('warehouse', models.CharField(blank=True, max_length=40, null=True)),
                ('employeeid', models.ForeignKey(blank=True, db_column='employeeid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseorders', to='employees.employee')),
                ('supplierid', models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.PROTECT, related_name='purchaseorders', to='ssafy_international.supplier')),
            ],
            options={
                'db_table': 'purchaseorder',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiptdate', models.DateField()),
                ('quantityordered', models.IntegerField()),
                ('quantityreceived', models.IntegerField()),
                ('qcstatus', models.CharField(max_length=20)),
                ('warehouse', models.CharField(blank=True, max_length=40, null=True)),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='ssafy_international.product')),
                ('purchaseorderid', models.ForeignKey(db_column='purchaseorderid', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'goodsreceipt',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unitcost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.FloatField(default=0.0)),
                ('linetotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.PROTECT, related_name='po_details', to='ssafy_international.product')),
                ('purchaseorderid', models.ForeignKey(db_column='purchaseorderid', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'purchaseorderdetail',
            },
        ),
    ]
